# Generated by Django 5.2.13 on 2026-04-20 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('identidad', models.CharField(max_length=20, unique=True)),
                ('telefono_casa', models.CharField(blank=True, max_length=20, null=True)),
                ('telefono_negocio', models.CharField(blank=True, max_length=20, null=True)),
                ('telefono_celular', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'clientes',
                'ordering': ['id_cliente'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('rol', models.CharField(choices=[('administrador', 'administrador'), ('asesor', 'asesor'), ('supervisor', 'supervisor')], max_length=20)),
                ('correo', models.EmailField(blank=True, max_length=100, null=True, unique=True)),
                ('clave', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'usuarios',
                'ordering': ['id_usuario'],
            },
        ),
        migrations.CreateModel(
            name='HistorialPrestamo',
            fields=[
                ('id_historial', models.AutoField(primary_key=True, serialize=False)),
                ('numero_prestamo', models.CharField(max_length=20)),
                ('producto', models.CharField(blank=True, max_length=50, null=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('interes', models.DecimalField(decimal_places=2, max_digits=12)),
                ('plazo', models.IntegerField(blank=True, null=True)),
                ('tasa', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('saldo', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('id_cliente', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.RESTRICT, to='api.cliente')),
            ],
            options={
                'db_table': 'historial_prestamos',
                'ordering': ['-id_historial'],
            },
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id_prestamo', models.AutoField(primary_key=True, serialize=False)),
                ('numero_prestamo', models.CharField(max_length=20, unique=True)),
                ('sucursal', models.CharField(blank=True, max_length=100, null=True)),
                ('ciclos', models.IntegerField(default=0)),
                ('supervisor', models.CharField(blank=True, max_length=100, null=True)),
                ('asesor', models.CharField(blank=True, max_length=100, null=True)),
                ('dias_mora', models.IntegerField(default=0)),
                ('categoria_crediticia', models.CharField(blank=True, max_length=50, null=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('plazo', models.IntegerField()),
                ('tasa_interes', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tipo_garantia', models.CharField(blank=True, max_length=50, null=True)),
                ('estado', models.CharField(choices=[('activo', 'activo'), ('pagado', 'pagado'), ('mora', 'mora'), ('cancelado', 'cancelado')], default='activo', max_length=20)),
                ('forma_pago', models.CharField(choices=[('semanal', 'semanal'), ('mensual', 'mensual'), ('quincenal', 'quincenal')], max_length=20)),
                ('forma_desembolso', models.CharField(choices=[('efectivo', 'efectivo'), ('transferencia', 'transferencia'), ('cheque', 'cheque')], max_length=20)),
                ('comision', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('producto', models.CharField(blank=True, max_length=50, null=True)),
                ('categoria', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_entrega', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('id_cliente', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.RESTRICT, to='api.cliente')),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.RESTRICT, to='api.usuario')),
            ],
            options={
                'db_table': 'prestamos',
                'ordering': ['-id_prestamo'],
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id_pago', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_pago', models.DateField()),
                ('documento', models.CharField(blank=True, max_length=50, null=True)),
                ('capital', models.DecimalField(decimal_places=2, max_digits=12)),
                ('interes', models.DecimalField(decimal_places=2, max_digits=12)),
                ('mora', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('id_prestamo', models.ForeignKey(db_column='id_prestamo', on_delete=django.db.models.deletion.RESTRICT, to='api.prestamo')),
            ],
            options={
                'db_table': 'pagos',
                'ordering': ['-fecha_pago', '-id_pago'],
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id_servicio', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_servicio', models.IntegerField()),
                ('nombre_servicio', models.CharField(max_length=100)),
                ('inicial', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('abono', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('porcentaje', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('id_prestamo', models.ForeignKey(db_column='id_prestamo', on_delete=django.db.models.deletion.RESTRICT, to='api.prestamo')),
            ],
            options={
                'db_table': 'servicios',
                'ordering': ['id_servicio'],
            },
        ),
    ]
