# Generated by Django 5.2.13 on 2026-04-27 00:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteDocumento',
            fields=[
                ('id_documento', models.AutoField(primary_key=True, serialize=False)),
                ('archivo', models.FileField(upload_to='clientes/documentos/%Y/%m/')),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('actor', models.CharField(default='Operador', max_length=100)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('id_cliente', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.CASCADE, to='api.cliente')),
            ],
            options={
                'db_table': 'cliente_documentos',
                'ordering': ['-creado_en', '-id_documento'],
            },
        ),
    ]
