# Generated by Django 5.2.13 on 2026-04-27 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_clientedocumento'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='expediente_completado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='expediente_estado',
            field=models.CharField(choices=[('borrador', 'borrador'), ('en_proceso', 'en_proceso'), ('completo', 'completo')], default='borrador', max_length=20),
        ),
        migrations.AddField(
            model_name='cliente',
            name='expediente_producto',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='expediente_tipo_perfil',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='notas_expediente',
            field=models.TextField(blank=True, null=True),
        ),
    ]
