# Generated by Django 5.2.13 on 2026-04-27 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_cliente_expediente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='estado',
            field=models.CharField(choices=[('pendiente_aprobacion', 'pendiente_aprobacion'), ('activo', 'activo'), ('pagado', 'pagado'), ('mora', 'mora'), ('cancelado', 'cancelado')], default='pendiente_aprobacion', max_length=20),
        ),
    ]
