# Generated by Django 5.2.13 on 2026-04-27 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_prestamo_pendiente_aprobacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('administrador', 'administrador'), ('asesor', 'asesor'), ('supervisor', 'supervisor'), ('cobranza_adm_jud', 'Cobranza administrativa / judicial (segun mora)')], max_length=40),
        ),
    ]
