# Generated by Django 5.2.13 on 2026-04-27 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_usuario_rol_cobranza'),
    ]

    operations = [
        migrations.CreateModel(
            name='GestionCobranza',
            fields=[
                ('id_gestion', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_gestion', models.CharField(choices=[('llamada', 'llamada'), ('visita', 'visita'), ('mensaje', 'mensaje'), ('acuerdo', 'acuerdo'), ('judicial', 'judicial')], max_length=20)),
                ('resultado', models.CharField(max_length=255)),
                ('promesa_pago_fecha', models.DateField(blank=True, null=True)),
                ('promesa_pago_monto', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('proxima_accion', models.CharField(blank=True, max_length=255, null=True)),
                ('actor', models.CharField(default='Cobranza', max_length=100)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('id_prestamo', models.ForeignKey(db_column='id_prestamo', on_delete=django.db.models.deletion.CASCADE, to='api.prestamo')),
            ],
            options={
                'db_table': 'gestion_cobranza',
                'ordering': ['-creado_en', '-id_gestion'],
            },
        ),
    ]
