# Generated by Django 5.2.13 on 2026-05-01 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_usuariorutacobranzadia'),
    ]

    operations = [
        migrations.CreateModel(
            name='HojaCobroImpresion',
            fields=[
                ('id_impresion', models.AutoField(primary_key=True, serialize=False)),
                ('numero_impresion', models.PositiveIntegerField(unique=True)),
                ('total_registros', models.PositiveIntegerField(default=0)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('generado_por', models.ForeignKey(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='impresiones_hoja_cobro', to='api.usuario')),
            ],
            options={
                'db_table': 'hoja_cobro_impresiones',
                'ordering': ['-creado_en', '-id_impresion'],
            },
        ),
    ]
