# Generated by Django 5.2.13 on 2026-06-22 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_prestamo_id_cartera'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='clave',
            field=models.CharField(help_text='DEPRECADO: no usar para autenticación. El acceso es vía Django User + JWT.', max_length=255),
        ),
    ]
